Main (#655)
* Update to address some staging/prod issues. (#654)

* Adding some code changes needed to support trcshell in staging and prod.  Stab at fixing carrier wedges.

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Karnveer Gill <karnveer_gill@trimble.com>
Co-authored-by: Karnveer Gill <101755160+KarnveerSGill@users.noreply.github.com>
Co-authored-by: meghan-bailey <107890930+meghan-bailey@users.noreply.github.com>

diff --git a/trcinit/vaultfiles/azure/trcagent/trc_templates/Vault/Tierceron/deploy/deploy.sh.tmpl b/trcinit/vaultfiles/azure/trcagent/trc_templates/Vault/Tierceron/deploy/deploy.sh.tmpl
--- a/trcinit/vaultfiles/azure/trcagent/trc_templates/Vault/Tierceron/deploy/deploy.sh.tmpl
+++ b/trcinit/vaultfiles/azure/trcagent/trc_templates/Vault/Tierceron/deploy/deploy.sh.tmpl
@@ -26,7 +26,7 @@ read VAULT_TOKEN
 echo "Enter environment: "
 read VAULT_ENV
 
-echo "Is this an agent utility deployment (Y or N): "
+echo "Is this plugin an agent (Y or N): "
 read VAULT_AGENT
 
 if [ "$VAULT_AGENT" = 'Y' ] || [ "$VAULT_AGENT" = 'y' ]; then
@@ -46,39 +46,20 @@ else
 fi
 
 
-if [ "$VAULT_ENV" = "prod" ] || [ "$VAULT_ENV" = "staging" ]; then
-    if [ "$PRE_CERTIFY" = "Y" ] || [ "$PRE_CERTIFY" = "yes" ] || [ "$PRE_CERTIFY" = "y" ]; then
-        if [ "$VAULT_AGENT" = 'Y' ] || [ "$VAULT_AGENT" = 'y' ]; then 
-            echo "Deploying agent"
-            trcplgtool -env=$VAULT_ENV -certify -addr=$VAULT_ADDR -token=$VAULT_TOKEN -insecure -pluginName=$TRC_PLUGIN_NAME-prod -sha256=$(cat target/$TRC_PLUGIN_NAME-prod.sha256) -pluginType=agent
-            certifystatus=$?
-            if [ $certifystatus -eq 0 ]; then       
-               echo "No problems encountered."
-               exit $certifystatus
-            else
-               echo "Unexpected certifyication errorerror."
-               exit $certifystatus
-            fi
+if [ "$PRE_CERTIFY" = "Y" ] || [ "$PRE_CERTIFY" = "yes" ] || [ "$PRE_CERTIFY" = "y" ]; then
+    if [ "$VAULT_AGENT" = 'Y' ] || [ "$VAULT_AGENT" = 'y' ]; then 
+        echo "Deploying agent"
+        trcplgtool -env=$VAULT_ENV -certify -addr=$VAULT_ADDR -token=$VAULT_TOKEN -insecure -pluginName=$TRC_PLUGIN_NAME -sha256=$(cat target/$TRC_PLUGIN_NAME.sha256) -pluginType=agent
+        certifystatus=$?
+        if [ $certifystatus -eq 0 ]; then       
+           echo "No problems encountered."
+           exit $certifystatus
         else
-            trcplgtool -env=$VAULT_ENV -certify -addr=$VAULT_ADDR -token=$VAULT_TOKEN -insecure -pluginName=$TRC_PLUGIN_NAME-prod -sha256=$(cat target/$TRC_PLUGIN_NAME-prod.sha256)
+           echo "Unexpected certifyication errorerror."
+           exit $certifystatus
         fi
-    fi
-else
-    if [ "$PRE_CERTIFY" = "Y" ] || [ "$PRE_CERTIFY" = "yes" ] || [ "$PRE_CERTIFY" = "y" ]; then
-        if [ "$VAULT_AGENT" = 'Y' ] || [ "$VAULT_AGENT" = 'y' ]; then 
-	        echo "Deploying agent"
-            trcplgtool -env=$VAULT_ENV -certify -addr=$VAULT_ADDR -token=$VAULT_TOKEN -insecure -pluginName=$TRC_PLUGIN_NAME -sha256=$(cat target/$TRC_PLUGIN_NAME.sha256) -pluginType=agent
-            certifystatus=$?
-            if [ $certifystatus -eq 0 ]; then       
-               echo "No problems encountered."
-               exit $certifystatus
-            else
-               echo "Unexpected certifyication errorerror."
-               exit $certifystatus
-            fi
-        else
-            trcplgtool -env=$VAULT_ENV -certify -addr=$VAULT_ADDR -token=$VAULT_TOKEN -insecure -pluginName=$TRC_PLUGIN_NAME -sha256=$(cat target/$TRC_PLUGIN_NAME.sha256)
-        fi
+    else
+        trcplgtool -env=$VAULT_ENV -certify -addr=$VAULT_ADDR -token=$VAULT_TOKEN -insecure -pluginName=$TRC_PLUGIN_NAME -sha256=$(cat target/$TRC_PLUGIN_NAME.sha256)
     fi
 fi
 
@@ -91,17 +72,10 @@ then
     echo "Local plugin registration skipping certification."
 else
     echo "Checking plugin deploy status."
-    if [ "$VAULT_ENV" = "prod" ] || [ "$VAULT_ENV" = "staging" ]; then
-    echo "Certifying plugin for env $VAULT_ENV."
-    trcplgtool -env=$VAULT_ENV -checkDeployed -addr=$VAULT_ADDR -token=$VAULT_TOKEN -insecure -pluginName=$TRC_PLUGIN_NAME-prod -sha256=$(cat target/$TRC_PLUGIN_NAME-prod.sha256)
-    status=$?
-    echo "Plugin certified with result $status."
-    else
     echo "Certifying plugin for env $VAULT_ENV."
     trcplgtool -env=$VAULT_ENV -checkDeployed -addr=$VAULT_ADDR -token=$VAULT_TOKEN -insecure -pluginName=$TRC_PLUGIN_NAME -sha256=$(cat target/$TRC_PLUGIN_NAME.sha256)
     status=$?
     echo "Plugin certified with result $status."
-    fi 
 
     if [ $status -eq 0 ]; then       
     echo "This version of the plugin has already been deployed - enabling for environment $VAULT_ENV."
@@ -128,86 +102,56 @@ echo "Disable and unregister old plugin."
 export VAULT_CLIENT_TIMEOUT=300s
 # Migrate to carrier maybe?
 vault secrets disable $TRC_PLUGIN_NAME/
+
+vault secrets list | grep $TRC_PLUGIN_NAME
+existingplugin=$?
+if [ $existingplugin -eq 0 ]; then       
+    echo "Plugin still mounted unexpectedly.  Manual intervention required to clean up before registration can proceed."
+    exit 1
+else
+    echo "All mounts cleared.  Continuing..."
+fi
 vault plugin deregister $TRC_PLUGIN_NAME
 
 sleep 12
 
-if [ "$VAULT_ENV" = "prod" ] || [ "$VAULT_ENV" = "staging" ]; then
-    # Just writing to vault will trigger the carrier plugin...
+if [ "$VAULT_PLUGIN_DIR" ]
+then
+    chmod 700 target/$TRC_PLUGIN_NAME
+    cp target/$TRC_PLUGIN_NAME $VAULT_PLUGIN_DIR
+    SHAVAL=$( cat target/$TRC_PLUGIN_NAME.sha256 )
+    sudo setcap cap_ipc_lock=+ep $VAULT_PLUGIN_DIR/$TRC_PLUGIN_NAME
+else
+    # Just writing to vault will trigger a copy...
     # First we set Copied to false...
     # This should also trigger the copy process...
     # It should return sha256 of copied plugin on success.
-    SHA256BUNDLE=$(vault write vaultcarrier/$VAULT_ENV plugin=$TRC_PLUGIN_NAME-prod)
+    SHA256BUNDLE=$(vault write vaultcarrier/$VAULT_ENV plugin=$TRC_PLUGIN_NAME token=$VAULT_ENV_TOKEN vaddress=$VAULT_ADDR )
     SHAVAL=$(echo $SHA256BUNDLE | awk '{print $6}')
-    
-    if [ "$SHAVAL" != "$FILESHAVAL" ]; then
-    echo "Carrier failed to deploy plugin.  Please try again."
-    exit -1
+
+    if [ "$SHAVAL" = "Failure" ]; then
+        echo "Failed to obtain sha256 for indicated plugin.   Refusing to continue."
+        exit -1
     fi
-
-    if [ "$SHAVAL" = "" ]; then
-    echo "Failed to obtain sha256 for indicated plugin.   Refusing to continue."
-    exit -1
-    fi
-
-    echo "Registering new plugin."
-    # This can be replaced with? https://developer.hashicorp.com/vault/api-docs/system/plugins-catalog#register-plugin
-    # POST to: curl -H "X-Vault-Token: $VAULT_TOKEN" https://vault.dexchadev.com:8020/v1/sys/plugins/catalog/secret/trc-vault-plugin
-    # Migrate to carrier maybe?
-    vault plugin register \
-            -command=$TRC_PLUGIN_NAME-prod \
-            -sha256=$(echo $SHAVAL) \
-            -args=`backendUUID=789` \
-            $TRC_PLUGIN_NAME-prod
-    echo "Enabling new plugin."
-    # This can be replaces with? https://developer.hashicorp.com/vault/api-docs/v1.4.x/system/mounts#enable-secrets-engine
-    # POST to: curl -H "X-Vault-Token: $VAULT_TOKEN" https://127.0.0.1:10001/v1/sys/mounts
-    # Migrate to carrie maybe?
-    vault secrets enable \
-            -path=$TRC_PLUGIN_NAME \
-            -plugin-name=$TRC_PLUGIN_NAME-prod \
-            -description="Tierceron Vault Plugin Prod" \
-            plugin
-else
-    if [ "$VAULT_PLUGIN_DIR" ]
-    then
-        chmod 700 target/$TRC_PLUGIN_NAME
-        cp target/$TRC_PLUGIN_NAME $VAULT_PLUGIN_DIR
-        SHAVAL=$( cat target/$TRC_PLUGIN_NAME.sha256 )
-        sudo setcap cap_ipc_lock=+ep $VAULT_PLUGIN_DIR/$TRC_PLUGIN_NAME
-    else
-        # Just writing to vault will trigger a copy...
-        # First we set Copied to false...
-        # This should also trigger the copy process...
-        # It should return sha256 of copied plugin on success.
-        SHA256BUNDLE=$(vault write vaultcarrier/$VAULT_ENV plugin=$TRC_PLUGIN_NAME token=$VAULT_ENV_TOKEN vaddress=$VAULT_ADDR )
-        SHAVAL=$(echo $SHA256BUNDLE | awk '{print $6}')
-
-        if [ "$SHAVAL" = "Failure" ]; then
-            echo "Failed to obtain sha256 for indicated plugin.   Refusing to continue."
-            exit -1
-        fi
-    fi
-
-    if [ "$SHAVAL" != "$FILESHAVAL" ]; then
-    echo "Carrier failed to deploy plugin.  Please try again."
-    exit -1
-    fi
-
-    echo "Registering new plugin."
-    vault plugin register \
-            -command=$TRC_PLUGIN_NAME \
-            -sha256=$(echo $SHAVAL) \
-            -args=`backendUUID=789` \
-            $TRC_PLUGIN_NAME
-    echo "Enabling new plugin."
-    vault secrets enable \
-            -path=$TRC_PLUGIN_NAME \
-            -plugin-name=$TRC_PLUGIN_NAME \
-            -description="Tierceron Vault Plugin" \
-            plugin
 fi
 
+if [ "$SHAVAL" != "$FILESHAVAL" ]; then
+    echo "Carrier failed to deploy plugin.  Please try again."
+    exit -1
+fi
+
+echo "Registering new plugin."
+vault plugin register \
+        -command=$TRC_PLUGIN_NAME \
+        -sha256=$(echo $SHAVAL) \
+        -args=`backendUUID=789` \
+        $TRC_PLUGIN_NAME
+echo "Enabling new plugin."
+vault secrets enable \
+        -path=$TRC_PLUGIN_NAME \
+        -plugin-name=$TRC_PLUGIN_NAME \
+        -description="Tierceron Vault Plugin" \
+        plugin
 
 #Activates/starts the deployed plugin.
 # Note: plugin should update deployed flag for itself.
