Comments for changes needed to deploy

diff --git a/installation/trccloud/terraform/azure/cloudboot/trc_templates/Vault/Tierceron/deploy/deploy.sh.tmpl b/installation/trccloud/terraform/azure/cloudboot/trc_templates/Vault/Tierceron/deploy/deploy.sh.tmpl
--- a/installation/trccloud/terraform/azure/cloudboot/trc_templates/Vault/Tierceron/deploy/deploy.sh.tmpl
+++ b/installation/trccloud/terraform/azure/cloudboot/trc_templates/Vault/Tierceron/deploy/deploy.sh.tmpl
@@ -77,6 +77,16 @@ if [ "$PRE_CERTIFY" = "Y" ] || [ "$PRE_CERTIFY" = "yes" ] || [ "$PRE_CERTIFY" = 
         echo "Certifying agent deployment tool plugin..."
         trcplgtool -env=$VAULT_ENV -certify -addr=$SECRET_VAULT_ADDR -token=$SECRET_VAULT_ENV_TOKEN -pluginName=$TRC_PLUGIN_NAME -sha256=target/$TRC_PLUGIN_NAME -pluginType=agent
         certifystatus=$?
+        if [[$TRC_PLUGIN_NAME == *exe]]; then 
+            if [ $certifystatus -eq 0 ]; then
+                echo "No certification problems encountered."
+                exit $certifystatus
+            else
+                echo "Unexpected certification error."
+                exit $certifystatus
+            fi
+        fi
+        echo "TODO: check if ends in exe then self checks (check certifystatus and exit 0 - done)"
         if [ $certifystatus -eq 0 ]; then
            echo "No certification problems encountered."
            exit $certifystatus
